<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'id' => 1,
                'title' => 'Full‑Stack Web Development Bootcamp',
                'description' => 'Kuasai skill praktis dari dasar hingga mahir dalam program intensif ini. Dirancang oleh Rudi Yesaya dari Google dengan materi yang langsung applicable di industri.',
                'short_description' => 'Belajar Full-Stack Web Development dari nol.',
                'mentor_name' => 'Rudi Yesaya',
                'mentor_company' => 'Google',
                'category' => 'Programming',
                'level' => 'Intermediate',
                'badge' => 'Bestseller',
                'rating' => 4.9,
                'students_count' => 12400,
                'price' => 'Rp 799.000',
                'progress' => 68,
                'color' => '#667eea',
                'mentor_id' => 301,
            ],
            [
                'id' => 2,
                'title' => 'Data Science & Machine Learning Masterclass',
                'description' => 'Pelajari alur lengkap data science: pembersihan data, visualisasi, model ML, dan deployment. Studi kasus nyata dari industri e‑commerce.',
                'short_description' => 'Dari data mentah sampai model siap produksi.',
                'mentor_name' => 'Siti Rahayu',
                'mentor_company' => 'Tokopedia',
                'category' => 'Data Science',
                'level' => 'Intermediate',
                'badge' => 'Popular',
                'rating' => 4.8,
                'students_count' => 8900,
                'price' => 'Rp 899.000',
                'progress' => 45,
                'color' => '#f093fb',
                'mentor_id' => 302,
            ],
            [
                'id' => 3,
                'title' => 'Flutter & Firebase – Build Real Apps',
                'description' => 'Bangun aplikasi mobile cross‑platform lengkap dengan backend Firebase, autentikasi, dan deployment ke Play Store / App Store.',
                'short_description' => 'Buat aplikasi nyata dengan Flutter dan Firebase.',
                'mentor_name' => 'Budi Santoso',
                'mentor_company' => 'Startup Edukasi',
                'category' => 'Mobile',
                'level' => 'Beginner',
                'badge' => 'New',
                'rating' => 4.7,
                'students_count' => 5600,
                'price' => 'Rp 649.000',
                'progress' => 20,
                'color' => '#4facfe',
                'mentor_id' => 303,
            ],
            [
                'id' => 4,
                'title' => 'DevOps with Docker & Kubernetes',
                'description' => 'Pelajari manajemen container, orkestrasi, CI/CD, dan best practice operasional untuk menjalankan aplikasi skala produksi.',
                'short_description' => 'Implementasi Docker, K8s, dan pipeline CI/CD.',
                'mentor_name' => 'Dewi Lestari',
                'mentor_company' => 'Gojek',
                'category' => 'DevOps',
                'level' => 'Advanced',
                'badge' => 'Top Rated',
                'rating' => 4.9,
                'students_count' => 7200,
                'price' => 'Rp 849.000',
                'progress' => 90,
                'color' => '#43e97b',
                'mentor_id' => 304,
            ],
            [
                'id' => 5,
                'title' => 'Laravel 11 – Web Development Mudah',
                'description' => 'Belajar Laravel 11 secara praktis: routing, Eloquent, API, dan deployment. Cocok untuk developer pemula yang ingin cepat produktif.',
                'short_description' => 'Framework Laravel 11 untuk pembuatan aplikasi web cepat.',
                'mentor_name' => 'Ahmad Fauzi',
                'mentor_company' => 'Freelance',
                'category' => 'Programming',
                'level' => 'Beginner',
                'badge' => 'Trending',
                'rating' => 4.6,
                'students_count' => 3800,
                'price' => 'Rp 599.000',
                'progress' => 35,
                'color' => '#fa709a',
                'mentor_id' => 305,
            ],
            [
                'id' => 6,
                'title' => 'UI/UX Design for Mobile & Web',
                'description' => 'Pelajari prinsip desain antarmuka, prototyping, dan user testing untuk membuat produk yang intuitif dan menarik.',
                'short_description' => 'Desain UI/UX praktis untuk produk digital.',
                'mentor_name' => 'Budi Santoso',
                'mentor_company' => 'Startup Edukasi',
                'category' => 'Design',
                'level' => 'Beginner',
                'badge' => null,
                'rating' => 4.5,
                'students_count' => 4200,
                'price' => 'Rp 549.000',
                'progress' => 10,
                'color' => '#ffecd2',
                'mentor_id' => 303,
            ],
            [
                'id' => 7,
                'title' => 'React JS – Dari Nol hingga Expert',
                'description' => 'Kuasi React modern, hooks, state management, dan optimasi performa dengan proyek‑proyek nyata yang meningkatkan portofolio Anda.',
                'short_description' => 'React dari dasar sampai tingkat mahir.',
                'mentor_name' => 'Rudi Yesaya',
                'mentor_company' => 'Google',
                'category' => 'Programming',
                'level' => 'Intermediate',
                'badge' => 'Bestseller',
                'rating' => 4.9,
                'students_count' => 15200,
                'price' => 'Rp 749.000',
                'progress' => 55,
                'color' => '#fbc2eb',
                'mentor_id' => 301,
            ],
            [
                'id' => 8,
                'title' => 'SQL for Data Analysis',
                'description' => 'Pelajari query SQL tingkat lanjut, optimasi, dan teknik analisis data untuk menyelesaikan problem bisnis secara efisien.',
                'short_description' => 'SQL praktis untuk analis data.',
                'mentor_name' => 'Siti Rahayu',
                'mentor_company' => 'Tokopedia',
                'category' => 'Data Science',
                'level' => 'Beginner',
                'badge' => null,
                'rating' => 4.7,
                'students_count' => 6300,
                'price' => 'Rp 499.000',
                'progress' => 80,
                'color' => '#a1c4fd',
                'mentor_id' => 302,
            ],
            [
                'id' => 9,
                'title' => 'Python for Automation & Scripting',
                'description' => 'Automasi tugas sehari‑hari dan pembuatan skrip efisien menggunakan Python: scraping, file processing, dan automation pipelines.',
                'short_description' => 'Gunakan Python untuk otomatisasi pekerjaan rutin.',
                'mentor_name' => 'Ahmad Fauzi',
                'mentor_company' => 'Freelance',
                'category' => 'Programming',
                'level' => 'Beginner',
                'badge' => 'Hot',
                'rating' => 4.4,
                'students_count' => 2800,
                'price' => 'Rp 449.000',
                'progress' => 25,
                'color' => '#fddb92',
                'mentor_id' => 305,
            ],
            [
                'id' => 10,
                'title' => 'Cloud Computing with AWS',
                'description' => 'Pelajari konsep cloud, layanan AWS utama, dan deployment aplikasi skala besar dengan praktik langsung dan studi kasus nyata.',
                'short_description' => 'Dasar dan praktik AWS untuk penerapan produksi.',
                'mentor_name' => 'Dewi Lestari',
                'mentor_company' => 'Gojek',
                'category' => 'DevOps',
                'level' => 'Advanced',
                'badge' => 'Expert',
                'rating' => 4.8,
                'students_count' => 5100,
                'price' => 'Rp 899.000',
                'progress' => 70,
                'color' => '#c2e9fb',
                'mentor_id' => 304,
            ],
        ];

        foreach ($courses as $c) {
            $courseData = $c;
            unset($courseData['progress']); // Remove progress, it's from enrollment

            $courseData['benefits'] = json_encode([
                'Sertifikat penyelesaian',
                'Akses seumur hidup',
                '10+ proyek nyata',
                'Mentoring 1-on-1',
            ]);

            $courseData['curriculum'] = json_encode([
                'Modul 1: Pengenalan & Setup',
                'Modul 2: Konsep Dasar',
                'Modul 3: Studi Kasus',
                'Modul 4: Project Akhir',
            ]);

            $courseData['resources'] = json_encode([
                ['title' => 'Source Code', 'type' => 'zip'],
                ['title' => 'E-Book PDF', 'type' => 'pdf'],
                ['title' => 'Cheat Sheet', 'type' => 'pdf'],
            ]);

            Course::create($courseData);
        }
    }
}