<?php

namespace Database\Seeders;

use App\Models\Resource;
use Illuminate\Database\Seeder;

class ResourceSeeder extends Seeder
{
    public function run(): void
    {
        $resources = [
            // ── Course 1: Full-Stack Web Development Bootcamp ──────────────────
            [
                'course_id' => 1,
                'title' => 'Source Code Lengkap Proyek',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course1/source-code.zip',
                'file_size' => 15_200_000,
                'order' => 1,
                'description' => 'Kumpulan source code untuk semua proyek dalam bootcamp ini.',
            ],
            [
                'course_id' => 1,
                'title' => 'E-Book: Panduan Web Development Modern',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course1/ebook-webdev.pdf',
                'file_size' => 4_800_000,
                'order' => 2,
                'description' => 'E-book referensi lengkap HTML, CSS, JavaScript, dan React.',
            ],
            [
                'course_id' => 1,
                'title' => 'Cheat Sheet CSS & Flexbox',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course1/cheatsheet-css.pdf',
                'file_size' => 850_000,
                'order' => 3,
                'description' => 'Cheat sheet ringkas properti CSS dan layout Flexbox.',
            ],
            [
                'course_id' => 1,
                'title' => 'Slide Presentasi Semua Modul',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course1/slides-all-modules.pdf',
                'file_size' => 12_000_000,
                'order' => 4,
                'description' => 'Kumpulan slide presentasi dari semua modul pembelajaran.',
            ],

            // ── Course 2: Data Science & Machine Learning ─────────────────────
            [
                'course_id' => 2,
                'title' => 'Dataset untuk Latihan',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course2/datasets.zip',
                'file_size' => 85_000_000,
                'order' => 1,
                'description' => 'Berbagai dataset dari e-commerce untuk praktik data science.',
            ],
            [
                'course_id' => 2,
                'title' => 'E-Book: Data Science dari Nol',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course2/ebook-datascience.pdf',
                'file_size' => 6_200_000,
                'order' => 2,
                'description' => 'Panduan lengkap mulai dari Python hingga model ML siap produksi.',
            ],
            [
                'course_id' => 2,
                'title' => 'Notebook Jupyter Semua Chapter',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course2/jupyter-notebooks.zip',
                'file_size' => 22_000_000,
                'order' => 3,
                'description' => 'File .ipynb untuk setiap chapter dari pembersihan data hingga deployment.',
            ],
            [
                'course_id' => 2,
                'title' => 'Cheat Sheet Machine Learning Algorithms',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course2/cheatsheet-ml.pdf',
                'file_size' => 1_200_000,
                'order' => 4,
                'description' => 'Ringkasan algoritma ML, kapan pakai apa, dan parameter penting.',
            ],

            // ── Course 3: Flutter & Firebase ─────────────────────────────────
            [
                'course_id' => 3,
                'title' => 'Project Starter (Flutter Template)',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course3/flutter-starter.zip',
                'file_size' => 8_500_000,
                'order' => 1,
                'description' => 'Template project Flutter yang sudah dilengkapi konfigurasi Firebase.',
            ],
            [
                'course_id' => 3,
                'title' => 'E-Book: Flutter untuk Pemula',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course3/ebook-flutter.pdf',
                'file_size' => 5_400_000,
                'order' => 2,
                'description' => 'Panduan lengkap Flutter widget, state management, dan Firebase integration.',
            ],
            [
                'course_id' => 3,
                'title' => 'Asset Icon & Gambar Aplikasi',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course3/assets-icons.zip',
                'file_size' => 18_000_000,
                'order' => 3,
                'description' => 'Kumpulan icon dan gambar asset untuk aplikasi mobile.',
            ],
            [
                'course_id' => 3,
                'title' => 'Cheat Sheet Widget Flutter',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course3/cheatsheet-flutter.pdf',
                'file_size' => 900_000,
                'order' => 4,
                'description' => 'Cheat sheet widget Flutter yang sering digunakan.',
            ],

            // ── Course 4: DevOps with Docker & Kubernetes ──────────────────────
            [
                'course_id' => 4,
                'title' => 'Dockerfile & Docker Compose Templates',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course4/docker-templates.zip',
                'file_size' => 3_200_000,
                'order' => 1,
                'description' => 'Template Dockerfile dan docker-compose.yml untuk berbagai stack aplikasi.',
            ],
            [
                'course_id' => 4,
                'title' => 'Kubernetes Manifest Files',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course4/k8s-manifests.zip',
                'file_size' => 4_100_000,
                'order' => 2,
                'description' => 'Contoh file YAML manifest Kubernetes untuk deployment, service, configmap, dll.',
            ],
            [
                'course_id' => 4,
                'title' => 'E-Book: DevOps Handbook Indonesia',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course4/ebook-devops.pdf',
                'file_size' => 7_800_000,
                'order' => 3,
                'description' => 'E-book panduan DevOps praktis dalam Bahasa Indonesia.',
            ],
            [
                'course_id' => 4,
                'title' => 'CI/CD Pipeline Scripts',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course4/cicd-scripts.zip',
                'file_size' => 2_400_000,
                'order' => 4,
                'description' => 'Script pipeline CI/CD untuk GitLab CI dan Jenkins.',
            ],
            [
                'course_id' => 4,
                'title' => 'Cheat Sheet Docker & K8s Commands',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course4/cheatsheet-docker-k8s.pdf',
                'file_size' => 750_000,
                'order' => 5,
                'description' => 'Ringkasan command Docker dan Kubernetes yang paling sering dipakai.',
            ],

            // ── Course 5: Laravel 11 ───────────────────────────────────────────
            [
                'course_id' => 5,
                'title' => 'Project Laravel 11 Starter',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course5/laravel11-starter.zip',
                'file_size' => 6_800_000,
                'order' => 1,
                'description' => 'Project Laravel 11 starter pack dengan authentication dan dashboard.',
            ],
            [
                'course_id' => 5,
                'title' => 'E-Book: Laravel 11 dari Dasar',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course5/ebook-laravel11.pdf',
                'file_size' => 8_200_000,
                'order' => 2,
                'description' => 'Panduan lengkap Laravel 11: routing, Eloquent, API, dan deployment.',
            ],
            [
                'course_id' => 5,
                'title' => 'API Collection (Postman)',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course5/postman-collection.zip',
                'file_size' => 45_000,
                'order' => 3,
                'description' => 'Postman collection untuk testing semua endpoint API di course ini.',
            ],
            [
                'course_id' => 5,
                'title' => 'Cheat Sheet Blade & Eloquent',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course5/cheatsheet-blade-eloquent.pdf',
                'file_size' => 1_100_000,
                'order' => 4,
                'description' => 'Cheat sheet sintaks Blade template dan query Eloquent.',
            ],

            // ── Course 6: UI/UX Design ────────────────────────────────────────
            [
                'course_id' => 6,
                'title' => 'Figma Source Files',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course6/figma-source.zip',
                'file_size' => 45_000_000,
                'order' => 1,
                'description' => 'File Figma lengkap untuk semua wireframe dan prototype di course ini.',
            ],
            [
                'course_id' => 6,
                'title' => 'Design System Kit',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course6/design-system-kit.zip',
                'file_size' => 28_000_000,
                'order' => 2,
                'description' => 'Component library dan design tokens untuk project design system.',
            ],
            [
                'course_id' => 6,
                'title' => 'E-Book: UI/UX Principles in Practice',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course6/ebook-uiux.pdf',
                'file_size' => 14_500_000,
                'order' => 3,
                'description' => 'E-book mendalam tentang prinsip UI/UX dan studi kasus nyata.',
            ],
            [
                'course_id' => 6,
                'title' => 'Moodboard & Color Palette References',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course6/moodboard-colors.zip',
                'file_size' => 52_000_000,
                'order' => 4,
                'description' => 'Koleksi moodboard, referensi warna, dan tipografi.',
            ],

            // ── Course 7: React JS ──────────────────────────────────────────────
            [
                'course_id' => 7,
                'title' => 'React Project Templates',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course7/react-templates.zip',
                'file_size' => 9_600_000,
                'order' => 1,
                'description' => 'Template project React dengan Vite, TypeScript, dan Redux setup.',
            ],
            [
                'course_id' => 7,
                'title' => 'E-Book: React Patterns & Best Practices',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course7/ebook-react.pdf',
                'file_size' => 5_900_000,
                'order' => 2,
                'description' => 'Panduan patterns React, hooks, dan optimasi performa.',
            ],
            [
                'course_id' => 7,
                'title' => 'Source Code Semua Proyek',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course7/source-code.zip',
                'file_size' => 19_500_000,
                'order' => 3,
                'description' => 'Source code lengkap dari setiap proyek yang dibangun di course ini.',
            ],
            [
                'course_id' => 7,
                'title' => 'Cheat Sheet React Hooks',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course7/cheatsheet-hooks.pdf',
                'file_size' => 650_000,
                'order' => 4,
                'description' => 'Ringkasan semua React hooks dengan contoh penggunaan.',
            ],

            // ── Course 8: SQL for Data Analysis ────────────────────────────────
            [
                'course_id' => 8,
                'title' => 'SQL Script untuk Latihan',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course8/sql-scripts.zip',
                'file_size' => 3_800_000,
                'order' => 1,
                'description' => 'File .sql untuk semua query latihan dari basic hingga advanced.',
            ],
            [
                'course_id' => 8,
                'title' => 'E-Book: SQL for Business Intelligence',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course8/ebook-sql.pdf',
                'file_size' => 4_300_000,
                'order' => 2,
                'description' => 'Panduan SQL untuk analisis bisnis dan data intelligence.',
            ],
            [
                'course_id' => 8,
                'title' => 'Sample Database (E-Commerce DB)',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course8/sample-database.zip',
                'file_size' => 120_000_000,
                'order' => 3,
                'description' => 'Database SQL lengkap dengan data sample e-commerce untuk analisis.',
            ],
            [
                'course_id' => 8,
                'title' => 'Cheat Sheet SQL Query Reference',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course8/cheatsheet-sql.pdf',
                'file_size' => 880_000,
                'order' => 4,
                'description' => 'Cheat sheet query SQL: SELECT, JOIN, subquery, window functions.',
            ],

            // ── Course 9: Python for Automation ────────────────────────────────
            [
                'course_id' => 9,
                'title' => 'Python Script Templates',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course9/python-scripts.zip',
                'file_size' => 2_100_000,
                'order' => 1,
                'description' => 'Template script Python untuk scraping, automation, dan file processing.',
            ],
            [
                'course_id' => 9,
                'title' => 'E-Book: Python Automation Handbook',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course9/ebook-python-automation.pdf',
                'file_size' => 5_600_000,
                'order' => 2,
                'description' => 'Panduan otomatisasi dengan Python: web scraping, email, Excel, dan cron.',
            ],
            [
                'course_id' => 9,
                'title' => 'Project Source Code',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course9/project-source.zip',
                'file_size' => 4_700_000,
                'order' => 3,
                'description' => 'Source code semua proyek automation yang dibangun di course ini.',
            ],
            [
                'course_id' => 9,
                'title' => 'Cheat Sheet Python Standard Library',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course9/cheatsheet-python.pdf',
                'file_size' => 920_000,
                'order' => 4,
                'description' => 'Ringkasan fungsi Python yang sering dipakai untuk automation.',
            ],

            // ── Course 10: Cloud Computing with AWS ────────────────────────────
            [
                'course_id' => 10,
                'title' => 'AWS Architecture Diagrams',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course10/aws-diagrams.zip',
                'file_size' => 8_200_000,
                'order' => 1,
                'description' => 'Diagram arsitektur AWS untuk semua deployment scenario di course ini.',
            ],
            [
                'course_id' => 10,
                'title' => 'CloudFormation Templates',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course10/cloudformation.zip',
                'file_size' => 5_400_000,
                'order' => 2,
                'description' => 'Template CloudFormation YAML untuk provisioning infrastruktur AWS.',
            ],
            [
                'course_id' => 10,
                'title' => 'E-Book: AWS in Action',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course10/ebook-aws.pdf',
                'file_size' => 9_800_000,
                'order' => 3,
                'description' => 'Panduan komprehensif layanan AWS utama dan best practice deployment.',
            ],
            [
                'course_id' => 10,
                'title' => 'AWS CLI & SDK Scripts',
                'type' => 'zip',
                'url' => 'https://example.com/resources/course10/aws-scripts.zip',
                'file_size' => 3_100_000,
                'order' => 4,
                'description' => 'Script AWS CLI dan SDK Python/Bash untuk automasi infrastruktur.',
            ],
            [
                'course_id' => 10,
                'title' => 'Cheat Sheet AWS Services',
                'type' => 'pdf',
                'url' => 'https://example.com/resources/course10/cheatsheet-aws.pdf',
                'file_size' => 1_400_000,
                'order' => 5,
                'description' => 'Ringkasan layanan AWS utama: EC2, S3, RDS, Lambda, VPC, dll.',
            ],
        ];

        foreach ($resources as $r) {
            Resource::updateOrCreate(
                ['course_id' => $r['course_id'], 'title' => $r['title']],
                $r
            );
        }
    }
}
